---

- name: Hostname -> WIN10
  win_hostname:
    name: win10
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required

- name: Set HostOnly IP Address
  win_shell: "New-NetIPAddress –InterfaceAlias Ethernet1 –AddressFamily IPv4 -IPAddress 10.1.1.3 –PrefixLength 24 -DefaultGateway 10.1.1.254"

- name: Set HostOnly DNS Address
  win_shell: "Set-DnsClientServerAddress -InterfaceAlias Ethernet1 -ServerAddresses 10.1.1.1,1.1.1.1"

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Check if existing PurpleLab directory
  win_stat:
    path: 'c:\PurpleLab'
  register: dir

- name: Git clone PurpleLab
  win_shell: git clone https://github.com/neokjames/PurpleLab.git
  args:
    chdir: 'c:\'
  when: not dir.stat.exists

- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Recurse c:\PurpleLab\Vagrant c:\vagrant

- name: Making Windows10 Great Again
  win_shell:  .\\MakeWindows10GreatAgain.ps1
  args:
    chdir: 'c:\vagrant\scripts'

- name: Join the Domain
  win_shell: .\\provision.ps1
  args:
    chdir: 'c:\vagrant\scripts'

- name: Update group policy
  win_shell: "gpupdate /force"

- name: Reboot Server
  win_reboot:
    msg: "Joined the domain. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 60

- name: Clear Event Logs
  win_shell: "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"


