- name: Download and extract Cribl
  become: yes
  unarchive:
    src: https://cdn.cribl.io/dl/2.2.2/cribl-2.2.2-daa210f8-linux-x64.tgz
    dest: /opt/
    creates: /opt/cribl/bin/
    remote_src: yes

- name: Install Cribl
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    /opt/cribl/bin/cribl boot-start enable -m systemd
    systemctl enable cribl
    systemctl start cribl

- name: Postinstall Tasks
  args: 
    executable: /bin/bash
  become: yes
  shell: |
    # Include Cribl in the PATH
    echo export PATH="$PATH:/opt/cribl/bin" >>~/.bashrc
